### ISSUE TITLE
Animation Question: Long-Range Melee Weapon

### ISSUE THREAD

**Issue by racingcow** [collinhover/impactplusplus#106]
Hello,

I am using impact++ on a top-down action RPG, and I am trying to make the main player use a whip for a weapon. The whip, when fully extended, should be several times longer than the size of the player's "normal" (walking) sprite size. Something like the whip from the Secret of Mana...

![whip-right-084](https://f.cloud.github.com/assets/1176637/1505895/32add7de-48f5-11e3-8322-9dc3152a292b.jpeg)
_Figure 1 - "Small" part of the whip_

![whip-right-085](https://f.cloud.github.com/assets/1176637/1505890/9665d2a0-48f4-11e3-8e6a-d576774d0ed6.jpeg)
_Figure 2 - "Extended" part of the whip_

I was wondering about the best way to handle this. So far, I have tried splitting the animation into two pieces. I have player's attack animation include the "small" part of the whip (during the backswing), and then create a secondary entity for the "extended" part of the whip. I show and animate this "extended" entity at the end of the player's animation.

This works, but it seems less than optimal, and I'm not sure of performance/maintenance implications yet. 

Other things I have thought of (but haven't yet tried) are...
1.  Make the entire whip ("small" and "extended" pieces) a separate entity and make it overlay the player.
2.  Make the size of the player be an large elongated rectangle, big enough to contain the entire whip animation.
3. Make the size of the player be its current size, but then change the size of the player dynamically (to accommodate the whip animation) when the user decides to attack.

Perhaps there is something else I haven't thought of that would make more sense. Does anyone have any recommendations on the best way to handle this sort of thing?

**Comment by collinhover** [comment]
I have a similar entity in the 3rd level/episode of http://collinhover.com/biofleet (try running too close to the lizard creature). In my case, I decided to create an ability, ig.AbilityEat, that extends the ig.AbilityMelee. The lizard has an "eat" animation, which includes the first part of the tongue and opening his mouth. The lizard's eat ability uses casting to show this "eat" animation and create the rest of the tongue as a separate static, non colliding entity. Because ig.AbilityMelee extends ig.AbilityDamage, there is no collision checking necessary. When the ability is activated, it searches automatically for the closest entity with type DAMAGEABLE and deals damage roughly around the time the "eat" animation completes (in my case, the entity needs to be DAMAGEABLE and EDIBLE type). At the end, the ability cleans up the tongue entity automatically.

This is certainly not the only way to do it, and if you want to be able to hit multiple targets you'd need to tweak it a bit to spawn an entity that extends the ig.Projectile abstract. This way it'll check for intersections and deal damage, but you also want to override that to make sure the projectile doesn't kill itself when it intersects (so it can hit multiple entities).

One thing I wouldn't do is increase the entity size (whether always or dynamically) to account for special animations. This will cause some less than desirable behavior with collisions and checks.

**Comment by racingcow** [comment]
Thanks for the advice, @collinhover. I'll give that a try. Also, as always, thanks for the hard work on this awesome library!
