### ISSUE TITLE
jump velocity doubles when adding multiple player entities

### ISSUE THREAD

**Issue by raygerrard** [collinhover/impactplusplus#11]
I created two different player entities and set player2.controllable = false; player1 is not rendered to the canvas and neither entity is controllable. when setting player2.controllable = true; player 2 is rendered but the speed of movement is doubled for both grounded and ungrounded actions. it appears that multiple player entities cannot be on the same level.

**Comment by collinhover** [comment]
Hmm I did not expect there to be a need for more than one player. Why do you need two player entities? Have you checked if setting controllable is affecting the player prototype object? Also the player class has a name property of "player" for fast retrieval/searching of the player, and names should be unique.

**Comment by raygerrard** [comment]
In my game  there are multiple players with different abilities and you switch between them. The name property was causing the issue, it works when giving player2 a unique one.

Thanks.

**Comment by collinhover** [comment]
Just a thought for performance, I would not have more than one player entity in the game in that case anyway, because both will be updated when only one needs it. Either consolidate all into one, for example you could have multiple ability sets that you swap between instead of player entities. Or create both player entities but keep all but the active one killed and stored in a pool.

**Comment by raygerrard** [comment]
i need to keep both entities visible at all times, I could spawn kill then spawn a dumb entity but idle players should still respond to the environment. i.e if a collision is made they respond in different ways even when not currently controllable. I cannot see another way of achieving this without spawning multiple instances and toggling the entity the camera follows. How much do you think this will degrade performance if I had upto 4 player instances?

**Comment by raygerrard** [comment]
collision is not detected when two player entities overlap, both are set to type A, checks against BOTH and collides FIXED. By changing either one of these entities to extend from the Character class instead, collisions are detected as expected.

**Comment by collinhover** [comment]
The player is just a character with extra input responses, so having multiple players should be no worse than multiple creatures or multiple kinematic entities really. Maybe I worry too much about performance :-)

**Comment by collinhover** [comment]
The issue with no collisions is the GROUP. They are of the same group, and entities in the same group do not check or collide. This is particularly useful for projectiles.

**Comment by raygerrard** [comment]
ok thanks Collin. I have fixed locally by adding a property to my player instances .checkAgainstAllGroups. I added a check to entity.js so the entity check method is called regardless if this property is set to true.

I can submit a pull request if you want this check in the library?

**Comment by collinhover** [comment]
Actually you shouldn't need the extra property (I think). Since the "group" property is a bitwise flag, and the comparison is that !( a.group & b.group ), if you set your entities to have a "group" of 0, the comparison will always be true and then they will collide/check against all groups. ( 0 & any number ) is always 0, I believe, and you save yourself an extra check.

**Comment by raygerrard** [comment]
your right that works, I had to add it after calling this.parent() in my init method as it calls this.initTypes() itself overwriting the default.
