### ISSUE TITLE
BackgroundMap repeat make some bugs

### ISSUE THREAD

**Issue by nraibaud** [collinhover/impactplusplus#25]
Whena i set a background of 1x32 @32 with repeat property, i have this problem:
- camera jumps
- Background does not repeat well

When turning of repeat, all is fine.

**Comment by collinhover** [comment]
I would guess the camera jumping is an unrelated issue, and I'll push some changes soon to fix some camera bugs. I'll take a look into this and see if I can replicate the issue. 

Can you post an image of the issue on your end please?

**Comment by nraibaud** [comment]
http://pbrd.co/1abkBJg
Seems to bug when resizing...
Because i try with a largest background repeat and when camera is at the end of the background size it make a whole and after re render the background for repeat.

**Comment by collinhover** [comment]
Looks like the issue was with the background map merging I added to improve performance, which does not work well with repeating backgrounds. The merge with repeat made it look like the camera was jumping, but it was actually the background rendering wrong.

Did the last commit (on the dev branch) fix the issue for you?

**Comment by nraibaud** [comment]
No the background does not repeat :/

**Comment by collinhover** [comment]
Using the dev branch?

Can you email me a zip file of your game? I'm not sure what is causing the issue for you... everything works on all the tests I've run on my end.
