### ISSUE TITLE
Creature Y Size and Wandering

### ISSUE THREAD

**Issue by TigerJ** [collinhover/impactplusplus#39]
Creatures with size Y greater than 16 seem to stop wandering. This can be replicated in the demo by changing the spike to have a size Y greater than 16.

I'm trying to look down in the creature wandering blocks to see what is causing this. I should note this is in the DEV branch

**Comment by collinhover** [comment]
Top down mode, side scrolling mode, or both?

**Comment by TigerJ** [comment]
Only checked Side Scrolling mode.

**Comment by collinhover** [comment]
I'll have time to check this out later today. I'm pretty sure that the issue is the creature thinks the next node in the wander path is ungrounded, and in this case spikes can't jump. So the creature is dumping the path because it isn't safe (it thinks it is going to fall off an edge). I'll need to account for that in the path movement code. Thanks for finding this!

**Comment by TigerJ** [comment]
Thanks for being so active!

**Comment by collinhover** [comment]
Okay, test with the latest commit. Does it work as intended?

**Comment by TigerJ** [comment]
![image](https://f.cloud.github.com/assets/1319169/982726/4c7c7214-0819-11e3-8737-f81d28ab6ce3.png)

PERFECT
