### ISSUE TITLE
'moveFrom' not working?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#86]
I have an entity I'd like to have move away from another entity.

So I do entity.moveFrom(anotherEntity)

But it doesn't move at all. have I missed something?

**Comment by collinhover** [comment]
It's possible the recent pathfinding changes affected moving from. That is one of the things I didn't have time to test, so I'll take a look now.

**Comment by collinhover** [comment]
Tested `moveFrom` and it is working as expected. Keep in mind that moving from is only available to characters, and then only if they have `performance === ig.CONFIG.DYNAMIC` and `canPathfind === true`. It is very possible that, in the case of a creature, it is trying to move to a prey / predator and that is conflicting with your manual `moveFrom` call. In the case of a creature, use the `predatorName`, `predatorClass`, `predatorType`, or `predatorGroup` properties to use moving from properly.

Moving from is also at best just a guess based on where the character is, where the character it is trying to move away from is, and which possible path is the cheapest that would take the character the furthest away. Sometimes it is possible for moving from to get backed into a corner. Move to is far more accurate, because it knows where it is going.

If you still can't get it to work, reopen the issue and give me some more information, such as the specifics on the entity and a screenshot of the situation.

**Comment by arakash92** [comment]
It turned out to be a problem on my end, thanks though.
