### ISSUE TITLE
Fade 'level' in and out using camera atmosphere?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#92]
So I'm trying to have my world/level fade in and out.

I have the following code:

``` javascript
camera.addAtmosphere(0);//turns to black instantly, right?
camera.removeAtmosphere(2);//fades out atmosphere over 2 seconds, right?
```

Doesn't seem to work :s

**Comment by collinhover** [comment]
The issue is likely that the atmosphere overlay is not yet added to the world when you remove it, so it never gets added at all. Remember that when you use `ig.game.spawnEntity` it creates the entity immediately, then puts the entity in a deferred list, and on the next update actually adds the entity to the game. Try this:

``` js
camera.addAtmosphere(0);
// check if atmosphere overlay is actually added to the game
if ( camera.atmosphereOverlay.added ) {
   camera.removeAtmosphere(2);
}
// otherwise, wait for the added signal and then remove
else {
    camera.atmosphereOverlay.onAdded.addOnce( function () {
       camera.removeAtmosphere(2);
    } );
}
```

**Comment by arakash92** [comment]
Ah, right. thanks!
