### ISSUE TITLE
EntityConversation.complete() runs at init?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#96]
I have an `EntityConversation` with a few messages and I'd like to run some code after all messages have been displayed.

However, the `complete` method runs both at init and when it's actually complete.

What's going on?

**Comment by collinhover** [comment]
The complete method is called by any trigger immediately after it has triggered. In the case of a conversation, it blocks the parent call in the complete until it is actually completed. This is something that should be changed, because it is confusing, but until then take a look at the conversation source code and do the same check it does in its complete method.

**Comment by collinhover** [comment]
FYI in the next push this will change to where anything that descends from `ig.EntityTrigger` can set `autoComplete: false` to avoid double calling the complete method. When setting `autoComplete: false`, it just means that the complete method will be called manually later in the trigger's process. For example, `ig.EntityConversation` will do this, and only call complete once the conversation is finished.

**Comment by arakash92** [comment]
I see. Well thanks!
